Added standalone plotting of arriba output
ClinicalGenomicsGBG/qd_rna pull request #2
Opened 2024-09-16 09:23 UTC by CarolinaPB

## Contents
Review deadline: 2024-09-30

Main reviewer: @fannyhb

### The What
Added standalone plotting of arriba output. Previously the output of the several fusion callers was merged while plotting. This has not been changed, but now the results of the arriba fusion detection are plotted individually.  

### The Why
Request from the clinicians who look at the qd_rna output to have a plot that only shows arriba output. The merged plot loses some information on the reading frame. 

### The How
Calling function to plot standalone arriba results to the rnafusion runner in modules/rnafusion.py. Defined function with parameters in modules/nextflow/src/util.py. Created script with command to run arriba using a container - modules/nextflow/src/run_arriba.sh. Added lines to import created function in modules/nextflow/__init__.py

### This [update](https://semver.org/) is:
- [ ] **MAJOR** - when you make incompatible API changes
- [X] **MINOR** - when you add functionality in a backwards compatible manner
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

## Test Procedure
Run workflow for a few samples

### Installation and initiation

### Tests

### Expected outcome
Standalone arriba plot is saved to arriba/fusions.pdf

## Verifications
- [ ] Code reviewed by @fannyhb
- [ ] Code tested by @fannyhb

2024-09-16 10:42 UTC, dodslaser commented on modules/nextflow/__init__.py
The `modules/nextflow` directory is an external module, and should usually not be touched. Otherwise cellophane will refuse to update the module, since any local changes would be overwritten.

Instead of defining it here, `plot_fusion_only_arriba` should probably be moved into `modules/rnafusion.py`.

2024-09-16 10:44 UTC, dodslaser commented on modules/nextflow/src/util.py
As commented above, instead of defining it here, `plot_fusion_only_arriba` should probably be moved into `modules/rnafusion.py`.

2024-09-16 10:49 UTC, dodslaser commented on modules/nextflow/src/run_arriba.sh
This script should be moved into the top-level `scripts` directory. When called with `executor.submit` the path will be `str(root / "scripts" / "run_arriba.sh")`. I would also prefer if the name of the script was a bit more descriptive (eg. `arriba_draw_fusions.sh`).

2024-09-16 10:53 UTC, dodslaser commented on modules/nextflow/src/util.py
> +            "-B /workspace/carolina/qd_rna/references:/references:ro",
The location of the Arriba references will be somewhere under the path specified in `config.rnafusion.genomes_base`.

2024-09-16 10:54 UTC, dodslaser commented on modules/nextflow/src/util.py
> +        str(Path(__file__).parent / "run_arriba.sh"),
When the script is moved to `scripts` this will need to change to reflect that.

2024-09-16 10:55 UTC, dodslaser commented on modules/rnafusion.py
> +from modules.nextflow import plot_fusion_only_arriba
`plot_fusion_only_arriba` should be defined in this file, not imported from `modules.nextflow`.

2024-09-16 10:59 UTC, dodslaser commented on modules/nextflow/src/run_arriba.sh
All scripts should start with `set -veo pipefail`, or UGE may not be able to correctly terminate them on SIGINT.

2024-09-16 11:12 UTC, dodslaser requested changes
Great start on this feature. Ideally, this should be fixed upstream (in `nfcore/rnafusion` and/or `fusionreport` specifically), but it is what it is. I added a few comments that must be addressed before merging.

Also, as this PR only implements a single feature, I would prefer if you combine your commits into a single one with a conventional commits-style message (eg. `feat: Standalone arriba visualization`).

Feel free to ask questions here or on slack and I will respond when I can.

Sidenote: It would probably be good to merge changes from `cellophane11` into `dev` and then move this PR to `dev`, since the `cellophane11` branch is currently used in "production".

2024-09-18 12:16 UTC, fannyhb commented
@dodslaser Can we merge cellophane11 into dev, and then let dev be merge into main?
Because we are using cellophane11 in production now, and we want to include Carolinas new changes in production as well.
and it makes sense to run stuff in production from main?

2024-09-18 16:16 UTC, dodslaser commented
@fannyhb Merge to dev and use that is fine, but cellophane 1.1.0 (which cellophane11 branch targets) is not released yet and looks like there are a few blockers on that front (see ClinicalGenomicsGBG/cellophane#16). Until the release is made I'd like to keep this in dev for now. I can take a look and see if there is anything major preventing the release.

2024-09-19 18:42 UTC, dodslaser commented
Cellophane 1.1.0 is now released and the cellophane11 branch has been merged to dev. I rebased this PR and made a few changes to streamline it a bit. Most importantly, the`rnafusion.arriba_standalone_refs` config option was added in place of the hard-coded path. This option is REQUIRED, so if this is merged, qd_rna will not start unless it is added to the relevant config (or passed via the equivalent  --rnafusion_arriba_standalone_refs flag).

I still feel like maintaining a separate set of references for standalone Arriba is suboptimal. @CarolinaPB, if I understood correctly, the problem was that there were too many files in `rnafusion.genomes_base`. Would it be possible to bind-mount only the relevant files from to somewhere Arriba can see it? Were there any required files missing?

I haven't tested any of this myself, so feel free to do that and if everything works we can merge this.

2024-09-23 11:39 UTC, dodslaser commented
I spent some time with this to get it working without the need for any additional references. Here are the key changes:

- References and Arriba version will be automatically detected from files in the `pipeline_info` folder. This way, we will always use the same references and version as `nf-core/rnafusion` uses. 
- I switched to Conda instead of Apptainer for installing Arriba, as this has built-in support in cellophane's executor.
- The `.bam` from `star_for_arriba` is sorted, indexed, and used to generate the coverage track. It shouldn't differ that much, but this is technically more correct, as it is the actual BAM used by Arriba.

I ran a very small test on only the Arriba standalone part. We should probably do a full test-run as well before deploying. Using down-sampled `.fastq` files will not work, as Arriba probably won't find any fusions.

2024-09-23 14:47 UTC, dodslaser approved these changes

2024-09-25 08:09 UTC, CarolinaPB commented
I successfully tested the full workflow with two samples.

2024-09-26 12:38 UTC, merged